export default [
	"Actor",
	"Alien",
	"Alien Abductee",
	"Amputee",
	"Astronaut",
	"Artist",
	"Babysitter",
	"Bartender",
	"Bank Robber",
	"Biker",
	"Beach Bum",
	"Beggar",
	"Biker",
	"Blind Date",
	"Big Foot",
	"Bouncer",
	"Bridesmade",
	"Bull Fighter",
	"Bungee Jumper",
	"Camp Counselor",
	"Camper",
	"Castaway",
	"Caveman",
	"Castaway",
	"Cheerleader",
	"Chef",
	"Class Clown",
	"Coach",
	"Coal Miner",
	"Clown",
	"Cowboy",
	"Comedian",
	"Cupid",
	"Couch Potato",
	"Dad",
	"Dictator",
	"Dare Devil",
	"Drill Sergeant",
	"Diva",
	"Dumpster Diver",
	"Doctor",
	"Executioner",
	"Dog",
	"Fire Fighter",
	"Fashion Model",
	"Forture Teller",
	"Fisherman",
	"Frat Boy",
	"Geek",
	"Gladiator",
	"Gambler",
	"Grandma",
	"Gangster",
	"Ghost",
	"Girl Scout",
	"Grave Robber",
	"High School Dropout",
	"Hippie",
	"Hitch Hiker",
	"Hobo",
	"Haunted House Actor",
	"High School Student",
	"Hostage",
	"Hunter",
	"Immigrant",
	"Insomniac",
	"Jaitor",
	"Kindergartener",
	"Life Guard",
	"Lovers",
	"Last Person on Earth",
	"Lawyer",
	"Lumberjack",
	"Little Red Riding-Hood",
	"Lottery Winner",
	"Masseuse",
	"Missionary",
	"Mad Scientist",
	"Mob Boss",
	"Magician",
	"Monk",
	"Mortician",
	"Nanny",
	"Navy Seal",
	"Newlywed",
	"Ninja",
	"Nurse",
	"Olympic Athlete",
	"Paper Boy",
	"Pharaoh",
	"Pirate",
	"Pizza Deliverer",
	"Party Animal",
	"Party Host",
	"Police Officer",
	"Pop Singer",
	"Politician",
	"Pregnant Woman",
	"Prisoner of War",
	"Prison Guard",
	"Priest",
	"Princess",
	"Pro Wrestler",
	"Prom Date",
	"Protester",
	"Quarterback",
	"Queen",
	"Rioter",
	"Robot",
	"Rock Star",
	"Roommate",
	"Rapper",
	"Referee",
	"Rock Climber",
	"Runaway",
	"School Bus Driver",
	"Soldier",
	"Space Colonist",
	"Santa",
	"Sports Fan",
	"Secret Admirer",
	"Sports Mascot",
	"Senior Citizen",
	"Spy",
	"Snowman",
	"Substitute Teacher",
	"Sorority Girl",
	"Tailgater",
	"Stewardess",
	"Tarzan",
	"Super Hero",
	"Taxi Driver",
	"Surfer",
	"Teenager",
	"Teacher",
	"Tourist",
	"The President",
	"Therapist",
	"Toddler",
	"Treasure Hunter",
	"Tree Hugger",
	"Trucker",
	"Vampire",
	"Villan",
	"Waitress",
	"Witch",
	"Wizard",
	"Zombie"
]